name: PR Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: colinbut/terraform-build-container:1.0.0
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: terraform validate
        run: terraform validate
      
      - name: run tflint
        run: tflint terraform

      - name: run tfsec
        run: tfsec